@startuml AppIdentityDbContextModelSnapshot
class AppIdentityDbContextModelSnapshot  {
    # <<override>> BuildModel(modelBuilder : ModelBuilder) : void
    + AppIdentityDbContextModelSnapshot()
}
ModelSnapshot <|-- AppIdentityDbContextModelSnapshot
@enduml