@startuml BlazorLayoutComponent
class BlazorLayoutComponent  {
    # <<override>> OnInitialized() : void
    + CallRequestRefresh() : void
    + BlazorLayoutComponent()
}
LayoutComponentBase <|-- BlazorLayoutComponent
@enduml