@startuml RefreshBroadcast
class RefreshBroadcast <<sealed>>  {
    + {static} <<readonly>> Instance : RefreshBroadcast <<get>>
    + <<event>> RefreshRequested : Action
    + CallRequestRefresh() : void
}
@enduml