@startuml CatalogItemViewModel
class CatalogItemViewModel  {
    + Id : int <<get>> <<set>>
    + Name : string? <<get>> <<set>>
    + PictureUri : string? <<get>> <<set>>
    + Price : decimal <<get>> <<set>>
    + CatalogItemViewModel()
}
@enduml