@startuml BasketWithItemsSpecification
class BasketWithItemsSpecification <<sealed>>  {
    + BasketWithItemsSpecification(basketId : int)
    + BasketWithItemsSpecification(buyerId : string)
}
"Specification`1" "<Basket>" <|-- BasketWithItemsSpecification
@enduml