@startuml CatalogItemNameSpecification
class CatalogItemNameSpecification  {
    + CatalogItemNameSpecification(catalogItemName : string)
}
"Specification`1" "<CatalogItem>" <|-- CatalogItemNameSpecification
@enduml