@startuml ICatalogItemViewModelService
!include ../ViewModels/CatalogItemViewModel.puml
interface ICatalogItemViewModelService  {
    + UpdateCatalogItem(viewModel : CatalogItemViewModel) : Task
}
ICatalogItemViewModelService ..> CatalogItemViewModel
@enduml