@startuml IdentityTokenClaimService
class IdentityTokenClaimService  {
    + IdentityTokenClaimService(userManager : UserManager<ApplicationUser>)
    + <<async>> GetTokenAsync(userName : string) : Task<string>
}
ITokenClaimsService <|.. IdentityTokenClaimService
@enduml