@startuml SlugifyParameterTransformer
class SlugifyParameterTransformer  {
    + TransformOutbound(value : object?) : string?
    + SlugifyParameterTransformer()
}
IOutboundParameterTransformer <|.. SlugifyParameterTransformer
@enduml