@startuml AuthenticateRequest
!include ../BaseRequest.puml
class AuthenticateRequest  {
    + Username : string <<get>> <<set>>
    + Password : string <<get>> <<set>>
    + AuthenticateRequest()
}
BaseRequest <|-- AuthenticateRequest
@enduml