@startuml UserInfo
class UserInfo  {
    + {static} <<readonly>> Anonymous : UserInfo
    + IsAuthenticated : bool <<get>> <<set>>
    + NameClaimType : string <<get>> <<set>>
    + RoleClaimType : string <<get>> <<set>>
    + Claims : IEnumerable<ClaimValue> <<get>> <<set>>
    + UserInfo()
}
@enduml