@startuml ChangePasswordViewModel
class ChangePasswordViewModel  {
    + OldPassword : string? <<get>> <<set>>
    + NewPassword : string? <<get>> <<set>>
    + ConfirmPassword : string? <<get>> <<set>>
    + StatusMessage : string? <<get>> <<set>>
    + ChangePasswordViewModel()
}
@enduml