@startuml SetPasswordViewModel
class SetPasswordViewModel  {
    + NewPassword : string? <<get>> <<set>>
    + ConfirmPassword : string? <<get>> <<set>>
    + StatusMessage : string? <<get>> <<set>>
    + SetPasswordViewModel()
}
@enduml