@startuml RegisterViewModel
class RegisterViewModel  {
    + Email : string? <<get>> <<set>>
    + Password : string? <<get>> <<set>>
    + ConfirmPassword : string? <<get>> <<set>>
    + RegisterViewModel()
}
@enduml