@startuml ResetPasswordViewModel
class ResetPasswordViewModel  {
    + Email : string? <<get>> <<set>>
    + Password : string? <<get>> <<set>>
    + ConfirmPassword : string? <<get>> <<set>>
    + Code : string? <<get>> <<set>>
    + ResetPasswordViewModel()
}
@enduml